# Generated by Django 4.1.6 on 2023-02-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('online_time', models.IntegerField(default=0)),
                ('praises', models.IntegerField(default=0)),
            ],
        ),
    ]
