# Generated by Django 4.1.6 on 2023-02-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='commits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='lines',
            field=models.IntegerField(default=0),
        ),
    ]
